/**
 * Data Dictionary Schema
 *
 * Design Philosophy: Modern Technical Documentation
 * - Clean hierarchy with generous whitespace
 * - High contrast typography for technical clarity
 * - Responsive grid-based layout with sidebar navigation
 *
 * This file contains the complete schema structure for the Customer Churn prediction project.
 */

export interface Column {
  id: string;
  name: string;
  dataType: string;
  nullable: boolean;
  description: string;
  businessMeaning?: string;
  example?: string;
  category?: "Raw" | "Engineered" | "Outcome" | "Identifier" | "PII";
  usedInModel?: boolean;
}

export interface Table {
  id: string;
  name: string;
  schema: string;
  description: string;
  columns: Column[];
  role?: string;
  importance?: number;
}

export interface Module {
  id: string;
  name: string;
  description: string;
  tables: Table[];
  importance?: number;
  role?: string;
}

export const schemaModules: Module[] = [
  {
    id: "customer-master",
    name: "Customer Master",
    description:
      "Thông tin định danh khách hàng và các trường raw trong bảng Customer Master.",
    importance: 5,
    role: "Anchor & label",
    tables: [
      {
        id: "customer-master-main",
        name: "customer_master",
        schema: "public",
        description: "Bảng chính chứa thông tin khách hàng",
        role: "Anchor & label",
        importance: 5,
        columns: [
          {
            id: "customer-id",
            name: "customer_id",
            dataType: "STRING/INTEGER",
            nullable: false,
            description: "ID duy nhất khách hàng (khóa join)",
            businessMeaning:
              "Key để ghép dữ liệu, không dùng trực tiếp làm feature",
            example: "CUST_000123",
            category: "Identifier",
            usedInModel: false,
          },
          {
            id: "signup-date",
            name: "signup_date",
            dataType: "DATE/TIMESTAMP",
            nullable: true,
            description: "Ngày đăng ký khách hàng",
            example: "2019-11-01",
            category: "Raw",
            usedInModel: false,
          },
          {
            id: "relationship-start-date",
            name: "relationship_start_date",
            dataType: "DATE/TIMESTAMP",
            nullable: true,
            description: "Ngày bắt đầu quan hệ thực sự",
            example: "2019-11-01",
            category: "Raw",
            usedInModel: false,
          },
          {
            id: "account-open-date",
            name: "account_open_date",
            dataType: "DATE/TIMESTAMP",
            nullable: true,
            description: "Ngày mở account (account-level)",
            category: "Raw",
            usedInModel: false,
          },
          {
            id: "dob",
            name: "date_of_birth",
            dataType: "DATE",
            nullable: true,
            description: "Ngày sinh",
            category: "Raw",
            usedInModel: false,
          },
          {
            id: "gender",
            name: "gender",
            dataType: "STRING",
            nullable: true,
            description: "Giới tính (M/F/O/U)",
            category: "Raw",
            usedInModel: false,
          },
          {
            id: "city",
            name: "city",
            dataType: "STRING",
            nullable: true,
            description: "Thành phố/thị trấn",
            category: "Raw",
            usedInModel: false,
          },
          {
            id: "region",
            name: "region",
            dataType: "STRING",
            nullable: true,
            description: "Vùng (mapping từ city)",
            example: "South",
            category: "Raw",
            usedInModel: true,
          },
          {
            id: "customer-type",
            name: "customer_type",
            dataType: "STRING",
            nullable: true,
            description: "retail / corporate / SME",
            category: "Raw",
            usedInModel: true,
          },
          {
            id: "segment",
            name: "segment",
            dataType: "STRING",
            nullable: true,
            description: "Phân đoạn marketing",
            category: "Raw",
            usedInModel: true,
          },
          {
            id: "tier",
            name: "tier",
            dataType: "STRING/INTEGER",
            nullable: true,
            description: "Hạng khách hàng",
            category: "Raw",
            usedInModel: true,
          },
          {
            id: "risk-rating",
            name: "risk_rating",
            dataType: "STRING/INTEGER",
            nullable: true,
            description: "Đánh giá rủi ro (Risk)",
            category: "Raw",
            usedInModel: false,
          },
          {
            id: "customer-name",
            name: "customer_name",
            dataType: "STRING",
            nullable: true,
            description: "Tên khách hàng (PII)",
            category: "PII",
            usedInModel: false,
          },
          {
            id: "phone",
            name: "phone",
            dataType: "STRING",
            nullable: true,
            description: "Số điện thoại (PII)",
            category: "PII",
            usedInModel: false,
          },
          {
            id: "email",
            name: "email",
            dataType: "STRING",
            nullable: true,
            description: "Email (PII)",
            category: "PII",
            usedInModel: false,
          },
          {
            id: "account-id",
            name: "account_id",
            dataType: "STRING/INTEGER",
            nullable: true,
            description: "ID account",
            category: "Identifier",
            usedInModel: false,
          },
          {
            id: "account-close-date",
            name: "account_close_date",
            dataType: "DATE/TIMESTAMP",
            nullable: true,
            description: "Ngày đóng account (OUTCOME)",
            category: "Outcome",
            usedInModel: false,
          },
          {
            id: "close-reason",
            name: "close_reason",
            dataType: "STRING",
            nullable: true,
            description: "Lý do đóng (OUTCOME)",
            category: "Outcome",
            usedInModel: false,
          },
          {
            id: "status",
            name: "status",
            dataType: "STRING",
            nullable: true,
            description: "Trạng thái account tại snapshot",
            category: "Raw",
            usedInModel: false,
          },
          {
            id: "kyc-status",
            name: "kyc_status",
            dataType: "STRING",
            nullable: true,
            description: "Trạng thái KYC",
            category: "Raw",
            usedInModel: false,
          },
        ],
      },
    ],
  },

  {
    id: "casa",
    name: "CASA",
    description:
      "Bảng giao dịch CASA — các trường raw (không bao gồm engineered features)",
    importance: 5,
    role: "Early churn",
    tables: [
      {
        id: "casa-monthly",
        name: "casa_monthly",
        schema: "public",
        description: "Dữ liệu CASA theo tháng",
        role: "Early churn signal",
        importance: 5,
        columns: [
          {
            id: "casa-id",
            name: "id",
            dataType: "STRING/INTEGER",
            nullable: false,
            description: "Row id trong nguồn CASA",
            category: "Identifier",
            usedInModel: false,
          },
          {
            id: "casa-customerid",
            name: "customerid",
            dataType: "STRING/INTEGER",
            nullable: false,
            description: "Mã khách hàng (join key)",
            category: "Identifier",
            usedInModel: false,
          },
          {
            id: "casa-snapshot-month",
            name: "snapshot_month",
            dataType: "YYYYMM/DATE",
            nullable: false,
            description: "Mốc snapshot để tính feature/label",
            category: "Raw",
            usedInModel: false,
          },
          {
            id: "casa-daily-avg-balance",
            name: "casa_daily_average_balance",
            dataType: "NUMERIC",
            nullable: true,
            description: "Daily average balance",
            category: "Raw",
            usedInModel: true,
          },
          {
            id: "casa-inflow",
            name: "casa_inflow",
            dataType: "NUMERIC",
            nullable: true,
            description: "Tổng tiền vào trong kỳ",
            category: "Raw",
            usedInModel: true,
          },
          {
            id: "casa-outflow",
            name: "casa_outflow",
            dataType: "NUMERIC",
            nullable: true,
            description: "Tổng tiền ra trong kỳ",
            category: "Raw",
            usedInModel: true,
          },
          {
            id: "casa-txn-count",
            name: "casa_transaction_count",
            dataType: "INTEGER",
            nullable: false,
            description: "Số giao dịch trong kỳ",
            category: "Raw",
            usedInModel: true,
          },
          {
            id: "casa-txn-avg-amount",
            name: "casa_transaction_avg_amount",
            dataType: "NUMERIC",
            nullable: true,
            description: "Giá trị trung bình mỗi giao dịch",
            category: "Raw",
            usedInModel: false,
          },
          {
            id: "casa-closing-balance",
            name: "casa_closing_balance",
            dataType: "NUMERIC",
            nullable: true,
            description: "Số dư cuối kỳ",
            category: "Raw",
            usedInModel: false,
          },
          {
            id: "casa-opening-balance",
            name: "casa_opening_balance",
            dataType: "NUMERIC",
            nullable: true,
            description: "Số dư đầu kỳ",
            category: "Raw",
            usedInModel: false,
          },
          {
            id: "casa-active-flag",
            name: "casa_active_flag",
            dataType: "BOOLEAN/INT",
            nullable: true,
            description: "Indicator có giao dịch trong kỳ trước (lagged)",
            category: "Raw",
            usedInModel: false,
          },
          {
            id: "casa-account-status",
            name: "casa_account_status",
            dataType: "STRING",
            nullable: true,
            description: "Trạng thái account (mapped)",
            category: "Raw",
            usedInModel: false,
          },
          {
            id: "casa-status-code",
            name: "casa_status_code",
            dataType: "STRING",
            nullable: true,
            description: "Mã trạng thái chi tiết",
            category: "Raw",
            usedInModel: false,
          },
          {
            id: "account-closure-date",
            name: "account_closure_date",
            dataType: "DATE/TIMESTAMP",
            nullable: true,
            description: "Ngày đóng account (label/outcome)",
            category: "Outcome",
            usedInModel: false,
          },
        ],
      },
    ],
  },

  {
    id: "loan",
    name: "Loan",
    description:
      "Bảng Loan — các trường raw (không bao gồm engineered features)",
    importance: 3,
    role: "Stress tài chính",
    tables: [
      {
        id: "loan-monthly",
        name: "loan_monthly",
        schema: "public",
        description: "Dữ liệu khoản vay theo tháng",
        role: "Financial stress indicator",
        importance: 3,
        columns: [
          {
            id: "loan-id",
            name: "id",
            dataType: "STRING/INTEGER",
            nullable: false,
            description: "Row id",
            category: "Identifier",
            usedInModel: false,
          },
          {
            id: "loan-customerid",
            name: "customerid",
            dataType: "STRING/INTEGER",
            nullable: false,
            description: "Mã định danh khách hàng",
            category: "Identifier",
            usedInModel: false,
          },
          {
            id: "loan-snapshot-month",
            name: "snapshot_month",
            dataType: "YYYYMM/DATE",
            nullable: false,
            description: "Tháng quan sát",
            category: "Raw",
            usedInModel: false,
          },
          {
            id: "loan-outstanding-balance",
            name: "loan_outstanding_balance",
            dataType: "NUMERIC",
            nullable: true,
            description: "Số dư nợ vay còn lại",
            category: "Raw",
            usedInModel: true,
          },
          {
            id: "loan-monthly-payment",
            name: "loan_monthly_payment",
            dataType: "NUMERIC",
            nullable: true,
            description: "Khoản thanh toán vay hàng tháng",
            category: "Raw",
            usedInModel: true,
          },
          {
            id: "loan-count",
            name: "loan_count",
            dataType: "INTEGER",
            nullable: true,
            description: "Số khoản vay",
            category: "Raw",
            usedInModel: true,
          },
          {
            id: "loan-payment-status",
            name: "loan_payment_status",
            dataType: "STRING",
            nullable: true,
            description: "Trạng thái thanh toán",
            category: "Raw",
            usedInModel: false,
          },
          {
            id: "loan-status",
            name: "loan_status",
            dataType: "STRING",
            nullable: true,
            description: "Trạng thái khoản vay (OUTCOME)",
            category: "Outcome",
            usedInModel: false,
          },
          {
            id: "loan-written-off",
            name: "loan_written_off",
            dataType: "BOOLEAN",
            nullable: true,
            description: "Loan written off flag",
            category: "Outcome",
            usedInModel: false,
          },
        ],
      },
    ],
  },

  {
    id: "credit-card",
    name: "Credit Card",
    description:
      "Bảng Credit Card — các trường raw (không bao gồm engineered features)",
    importance: 4,
    role: "Engagement",
    tables: [
      {
        id: "credit-card-monthly",
        name: "credit_card_monthly",
        schema: "public",
        description: "Dữ liệu thẻ tín dụng theo tháng",
        role: "Customer engagement indicator",
        importance: 4,
        columns: [
          {
            id: "cc-customerid",
            name: "customerid",
            dataType: "STRING/INTEGER",
            nullable: false,
            description: "Mã định danh khách hàng",
            category: "Identifier",
            usedInModel: false,
          },
          {
            id: "cc-snapshot-month",
            name: "snapshot_month",
            dataType: "YYYYMM/DATE",
            nullable: false,
            description: "Tháng quan sát",
            category: "Raw",
            usedInModel: false,
          },
          {
            id: "cc-transaction-count",
            name: "credit_card_transaction_count",
            dataType: "INTEGER",
            nullable: true,
            description: "Số giao dịch thẻ tín dụng",
            category: "Raw",
            usedInModel: true,
          },
          {
            id: "cc-spending",
            name: "credit_card_spending",
            dataType: "NUMERIC",
            nullable: true,
            description: "Tổng chi tiêu trên thẻ",
            category: "Raw",
            usedInModel: true,
          },
          {
            id: "cc-utilization-rate",
            name: "credit_card_utilization_rate",
            dataType: "NUMERIC",
            nullable: true,
            description: "Tỷ lệ sử dụng hạn mức",
            category: "Raw",
            usedInModel: true,
          },
          {
            id: "cc-outstanding-balance",
            name: "credit_card_outstanding_balance",
            dataType: "NUMERIC",
            nullable: true,
            description: "Số dư thẻ",
            category: "Raw",
            usedInModel: true,
          },
          {
            id: "card-product-type",
            name: "card_product_type",
            dataType: "STRING",
            nullable: true,
            description: "Loại sản phẩm thẻ",
            category: "Raw",
            usedInModel: false,
          },
          {
            id: "statement-balance",
            name: "statement_balance",
            dataType: "NUMERIC",
            nullable: true,
            description: "Số dư trên sao kê",
            category: "Raw",
            usedInModel: false,
          },
          {
            id: "minimum-due",
            name: "minimum_due",
            dataType: "NUMERIC",
            nullable: true,
            description: "Số tiền tối thiểu phải trả",
            category: "Raw",
            usedInModel: false,
          },
          {
            id: "payment-amount",
            name: "payment_amount",
            dataType: "NUMERIC",
            nullable: true,
            description: "Số tiền đã thanh toán",
            category: "Raw",
            usedInModel: false,
          },
          {
            id: "auto-debit-flag",
            name: "auto_debit_flag",
            dataType: "BOOLEAN",
            nullable: true,
            description: "Tự động trích nợ",
            category: "Raw",
            usedInModel: false,
          },
          {
            id: "cc-count",
            name: "credit_card_count",
            dataType: "INTEGER",
            nullable: true,
            description: "Số thẻ",
            category: "Raw",
            usedInModel: true,
          },
          {
            id: "cc-payment-status",
            name: "credit_card_payment_status",
            dataType: "STRING",
            nullable: true,
            description: "Trạng thái thanh toán thẻ",
            category: "Raw",
            usedInModel: false,
          },
          {
            id: "cc-has-arrears",
            name: "credit_card_has_arrears",
            dataType: "BOOLEAN",
            nullable: true,
            description: "Có trễ hạn không",
            category: "Raw",
            usedInModel: false,
          },
          {
            id: "cc-limit",
            name: "credit_card_limit",
            dataType: "NUMERIC",
            nullable: true,
            description: "Hạn mức thẻ",
            category: "Raw",
            usedInModel: true,
          },
        ],
      },
    ],
  },

  {
    id: "demographic",
    name: "Demographic",
    description: "Các trường nhân khẩu học (Customer-level)",
    importance: 2,
    role: "Explain & segment",
    tables: [
      {
        id: "demographic-main",
        name: "demographic",
        schema: "public",
        description: "Thông tin nhân khẩu học của khách hàng",
        role: "Segmentation & interpretation",
        importance: 2,
        columns: [
          {
            id: "demo-customerid",
            name: "customerid",
            dataType: "STRING/INTEGER",
            nullable: false,
            description: "Mã định danh khách hàng",
            category: "Identifier",
            usedInModel: false,
          },
          {
            id: "demo-age",
            name: "customer_age",
            dataType: "INTEGER",
            nullable: true,
            description: "Tuổi khách hàng",
            category: "Raw",
            usedInModel: true,
          },
          {
            id: "demo-income",
            name: "income_level",
            dataType: "NUMERIC/STRING",
            nullable: true,
            description: "Thu nhập hoặc phân khúc thu nhập",
            category: "Raw",
            usedInModel: true,
          },
          {
            id: "demo-employment",
            name: "employment_status",
            dataType: "STRING",
            nullable: true,
            description: "Trạng thái việc làm",
            category: "Raw",
            usedInModel: true,
          },
          {
            id: "product-count",
            name: "product_count",
            dataType: "INTEGER",
            nullable: true,
            description: "Số lượng sản phẩm sở hữu",
            category: "Raw",
            usedInModel: true,
          },
          {
            id: "occupation",
            name: "occupation",
            dataType: "STRING",
            nullable: true,
            description: "Nghề nghiệp",
            category: "Raw",
            usedInModel: false,
          },
          {
            id: "residence-location",
            name: "residence_location",
            dataType: "STRING",
            nullable: true,
            description: "Địa điểm cư trú",
            category: "Raw",
            usedInModel: false,
          },
          {
            id: "channel-preference",
            name: "channel_preference",
            dataType: "STRING",
            nullable: true,
            description: "Ưu tiên kênh giao dịch",
            category: "Raw",
            usedInModel: false,
          },
          {
            id: "created-date",
            name: "created_date",
            dataType: "DATE/TIMESTAMP",
            nullable: true,
            description: "Ngày tạo hồ sơ",
            category: "Raw",
            usedInModel: false,
          },
        ],
      },
    ],
  },

  {
    id: "channel-usage",
    name: "Channel Usage",
    description:
      "Các trường raw về hành vi sử dụng kênh số (digital/channel activity)",
    importance: 5,
    role: "Digital early churn",
    tables: [
      {
        id: "channel-usage-monthly",
        name: "channel_usage_monthly",
        schema: "public",
        description: "Hành vi sử dụng kênh số theo tháng",
        role: "Digital engagement & early churn signal",
        importance: 5,
        columns: [
          {
            id: "ch-customerid",
            name: "customerid",
            dataType: "STRING/INTEGER",
            nullable: false,
            description: "Mã định danh khách hàng",
            category: "Identifier",
            usedInModel: false,
          },
          {
            id: "ch-snapshot-month",
            name: "snapshot_month",
            dataType: "YYYYMM/DATE",
            nullable: false,
            description: "Tháng quan sát",
            category: "Raw",
            usedInModel: false,
          },
          {
            id: "channel-type",
            name: "channel_type",
            dataType: "STRING",
            nullable: true,
            description: "Loại kênh",
            category: "Raw",
            usedInModel: false,
          },
          {
            id: "login-count",
            name: "login_count",
            dataType: "INTEGER",
            nullable: true,
            description: "Số lần đăng nhập ứng dụng/web",
            category: "Raw",
            usedInModel: true,
          },
          {
            id: "transaction-count",
            name: "transaction_count",
            dataType: "INTEGER",
            nullable: true,
            description: "Số giao dịch trên kênh",
            category: "Raw",
            usedInModel: true,
          },
          {
            id: "transaction-amount",
            name: "transaction_amount",
            dataType: "NUMERIC",
            nullable: true,
            description: "Tổng giá trị giao dịch",
            category: "Raw",
            usedInModel: true,
          },
          {
            id: "active-flag",
            name: "active_flag",
            dataType: "BOOLEAN",
            nullable: true,
            description: "Indicator hoạt động",
            category: "Raw",
            usedInModel: false,
          },
          {
            id: "last-activity-date",
            name: "last_activity_date",
            dataType: "DATE/TIMESTAMP",
            nullable: true,
            description: "Ngày tương tác gần nhất",
            category: "Raw",
            usedInModel: false,
          },
          {
            id: "device-type",
            name: "device_type",
            dataType: "STRING",
            nullable: true,
            description: "Loại thiết bị",
            category: "Raw",
            usedInModel: false,
          },
          {
            id: "failed-login-count",
            name: "failed_login_count",
            dataType: "INTEGER",
            nullable: true,
            description: "Số lần đăng nhập thất bại",
            category: "Raw",
            usedInModel: false,
          },
          {
            id: "session-duration",
            name: "session_duration",
            dataType: "NUMERIC",
            nullable: true,
            description: "Thời lượng phiên",
            category: "Raw",
            usedInModel: false,
          },
        ],
      },
    ],
  },

  {
    id: "customer-interaction",
    name: "Customer Interaction",
    description: "Các trường raw về tương tác khách hàng, tickets và khiếu nại",
    importance: 3,
    role: "Experience-driven churn",
    tables: [
      {
        id: "customer-interaction-main",
        name: "customer_interaction",
        schema: "public",
        description: "Lịch sử tương tác và khiếu nại của khách hàng",
        role: "Customer experience & satisfaction",
        importance: 3,
        columns: [
          {
            id: "ci-customerid",
            name: "customerid",
            dataType: "STRING/INTEGER",
            nullable: false,
            description: "Mã định danh khách hàng",
            category: "Identifier",
            usedInModel: false,
          },
          {
            id: "ci-interaction-id",
            name: "interaction_id",
            dataType: "STRING/INTEGER",
            nullable: false,
            description: "ID tương tác",
            category: "Identifier",
            usedInModel: false,
          },
          {
            id: "ci-date",
            name: "interaction_date",
            dataType: "DATE/TIMESTAMP",
            nullable: true,
            description: "Ngày tương tác",
            category: "Raw",
            usedInModel: false,
          },
          {
            id: "ci-channel",
            name: "interaction_channel",
            dataType: "STRING",
            nullable: true,
            description: "Kênh tương tác",
            category: "Raw",
            usedInModel: false,
          },
          {
            id: "ci-type",
            name: "interaction_type",
            dataType: "STRING",
            nullable: true,
            description: "Loại tương tác",
            category: "Raw",
            usedInModel: false,
          },
          {
            id: "ci-reason",
            name: "interaction_reason",
            dataType: "STRING",
            nullable: true,
            description: "Lý do tương tác",
            category: "Raw",
            usedInModel: false,
          },
          {
            id: "ci-status",
            name: "interaction_status",
            dataType: "STRING",
            nullable: true,
            description: "Trạng thái tương tác",
            category: "Raw",
            usedInModel: false,
          },
          {
            id: "ci-resolution",
            name: "resolution_code",
            dataType: "STRING",
            nullable: true,
            description: "Mã giải quyết",
            category: "Raw",
            usedInModel: false,
          },
          {
            id: "ci-priority",
            name: "priority_level",
            dataType: "STRING/INTEGER",
            nullable: true,
            description: "Mức độ ưu tiên",
            category: "Raw",
            usedInModel: false,
          },
          {
            id: "ci-assigned-team",
            name: "assigned_team",
            dataType: "STRING",
            nullable: true,
            description: "Team được giao",
            category: "Raw",
            usedInModel: false,
          },
          {
            id: "ci-text",
            name: "interaction_text",
            dataType: "TEXT",
            nullable: true,
            description: "Nội dung tương tác (nên mask/anonymize)",
            category: "PII",
            usedInModel: false,
          },
        ],
      },
    ],
  },

  {
    id: "campaign-response",
    name: "Campaign Response",
    description:
      "Các trường raw liên quan đến chiến dịch marketing và phản hồi",
    importance: 2,
    role: "Retention strategy",
    tables: [
      {
        id: "campaign-response-main",
        name: "campaign_response",
        schema: "public",
        description: "Phản hồi của khách hàng đối với các chiến dịch marketing",
        role: "Marketing effectiveness & retention",
        importance: 2,
        columns: [
          {
            id: "camp-customerid",
            name: "customerid",
            dataType: "STRING/INTEGER",
            nullable: false,
            description: "Mã định danh khách hàng",
            category: "Identifier",
            usedInModel: false,
          },
          {
            id: "camp-campaign-id",
            name: "campaign_id",
            dataType: "STRING/INTEGER",
            nullable: false,
            description: "ID chiến dịch",
            category: "Identifier",
            usedInModel: false,
          },
          {
            id: "camp-campaign-type",
            name: "campaign_type",
            dataType: "STRING",
            nullable: true,
            description: "Loại chiến dịch",
            category: "Raw",
            usedInModel: false,
          },
          {
            id: "camp-campaign-channel",
            name: "campaign_channel",
            dataType: "STRING",
            nullable: true,
            description: "Kênh chiến dịch",
            category: "Raw",
            usedInModel: false,
          },
          {
            id: "camp-start-date",
            name: "campaign_start_date",
            dataType: "DATE/TIMESTAMP",
            nullable: true,
            description: "Ngày bắt đầu chiến dịch",
            category: "Raw",
            usedInModel: false,
          },
          {
            id: "camp-end-date",
            name: "campaign_end_date",
            dataType: "DATE/TIMESTAMP",
            nullable: true,
            description: "Ngày kết thúc chiến dịch",
            category: "Raw",
            usedInModel: false,
          },
          {
            id: "camp-sent-date",
            name: "campaign_sent_date",
            dataType: "DATE/TIMESTAMP",
            nullable: true,
            description: "Ngày gửi chiến dịch",
            category: "Raw",
            usedInModel: false,
          },
          {
            id: "camp-response-flag",
            name: "campaign_response_flag",
            dataType: "BOOLEAN",
            nullable: true,
            description: "Khách hàng có phản hồi hay không",
            category: "Raw",
            usedInModel: false,
          },
          {
            id: "camp-response-date",
            name: "response_date",
            dataType: "DATE/TIMESTAMP",
            nullable: true,
            description: "Ngày phản hồi",
            category: "Raw",
            usedInModel: false,
          },
          {
            id: "camp-response-type",
            name: "response_type",
            dataType: "STRING",
            nullable: true,
            description: "Loại phản hồi",
            category: "Raw",
            usedInModel: false,
          },
          {
            id: "camp-offer-type",
            name: "offer_type",
            dataType: "STRING",
            nullable: true,
            description: "Loại ưu đãi",
            category: "Raw",
            usedInModel: false,
          },
        ],
      },
    ],
  },
];

export function getModuleById(id: string): Module | undefined {
  return schemaModules.find((m) => m.id === id);
}

export function getTableById(tableId: string): Table | undefined {
  for (const module of schemaModules) {
    const table = module.tables.find((t) => t.id === tableId);
    if (table) return table;
  }
  return undefined;
}

export function getAllTables(): Table[] {
  return schemaModules.flatMap((m) => m.tables);
}
